version: '3.8'

services:
  mysql_db:  # Nombre del servicio
    image: mysql:8.0  # Versi칩n de MySQL
    container_name: mysql_bbdd_I3G2  # Nombre del contenedor
    environment:
      MYSQL_ROOT_PASSWORD: admin124  # Contrase침a de acceso Obligatoria
      MYSQL_DATABASE: usuarios  # DB creada al inicio
      MYSQL_USER: useradmin  # Usuario admin
      MYSQL_PASSWORD: adminpass  # Contrase침a del admin
    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos
    ports:
      - "3306:3306"  # Puerto: Host:Contenedor
    restart: always  # Reinicio autom치tico de la BBDD

volumes:
  mysql_data:  # Volumen para persistir datos